using System;
using System.Collections;
using System.Collections.Generic;
using MrMoonlight.Data;
using UnityEngine;

namespace MrMoonlight.Enemies
{
    /// <summary>
    /// Burns a dead enemy away and frees it (MRM-85, Carlos 2026-09-30, Legion mode). The look is the
    /// INab "Burn Dissolve" (AST-063, orange glowing edge, charred band, noisy front) ported into RetroLit so
    /// the corpse keeps its retro look right up to the moment it burns: the dissolve material is a variant
    /// of the normal one with <c>_USE_DISSOLVE</c> on, swapped in only when the dissolve starts.
    ///
    /// Timeline, after <see cref="CorpseOptimizer.Settle"/>: wait <see cref="MoonlightTunables.CorpseDissolveDelay"/>,
    /// burn the body (<see cref="MoonlightTunables.CorpseDissolveDuration"/>, skipped when no camera sees it),
    /// then dissolve the dropped lamp and props while the lamp light dims to zero
    /// (<see cref="MoonlightTunables.CorpseLampDissolveDuration"/>), then destroy everything that belonged to the
    /// enemy: body, drops, culling proxy and registrations, so nothing of it stays in memory.
    ///
    /// Sits on the enemy prefab so the dissolve material variants are serialized into the build (shader
    /// variants are stripped otherwise). The variants are generated by the menu
    /// <c>Mr. Moonlight/Corpse Dissolve/Rebuild Material Variants</c>. Story mode turns
    /// <see cref="MoonlightTunables.CorpseDissolveEnabled"/> off (corpses stay).
    /// </summary>
    [AddComponentMenu("Mr. Moonlight/Enemies/Corpse Dissolve")]
    public sealed class CorpseDissolve : MonoBehaviour
    {
        [Serializable]
        public struct MaterialPair
        {
            [Tooltip("The material the renderer normally uses.")]
            public Material source;

            [Tooltip("Variant of it with the dissolve feature on. Generated by the Corpse Dissolve menu.")]
            public Material dissolve;
        }

        [Tooltip("Normal material -> dissolve variant, for the body, the lamp and every dropped prop.")]
        [SerializeField] private MaterialPair[] materials = new MaterialPair[0];

        private static readonly int AmountId = Shader.PropertyToID("_DissolveAmount");
        private static readonly int MinYId = Shader.PropertyToID("_DissolveMinY");
        private static readonly int MaxYId = Shader.PropertyToID("_DissolveMaxY");

        /// <summary>Editor tool hook: replaces the pair list.</summary>
        public void SetMaterials(MaterialPair[] pairs) => materials = pairs;

        private sealed class Group
        {
            public Renderer[] Renderers;
            public MaterialPropertyBlock Block = new MaterialPropertyBlock();
        }

        /// <summary>The whole timeline. Runs as a coroutine on the enemy; ends by destroying it.</summary>
        public IEnumerator Run()
        {
            MoonlightTunables t = Tunables.I;
            yield return new WaitForSeconds(t.CorpseDissolveDelay);
            if (this == null) yield break;
            float startedAt = Time.time;

            // 1. The body.
            var bodyRenderers = new List<Renderer>();
            // Every body renderer, even one the culler has switched off right now: if the player turns toward
            // it mid-burn the culler re-enables it, and it must already be carrying the dissolve material.
            foreach (Renderer r in GetComponentsInChildren<Renderer>(false))
            {
                if (!(r is ParticleSystemRenderer)) bodyRenderers.Add(r);
            }

            Group body = Prepare(bodyRenderers);
            bool seen = false;
            foreach (Renderer r in bodyRenderers) seen |= r.isVisible;
            Debug.Log($"[CORPSE] dissolve body '{name}': {bodyRenderers.Count} renderers, seen {seen}, duration {(seen ? t.CorpseDissolveDuration : 0f):0.0}s");
            yield return Burn(new[] { body }, seen ? t.CorpseDissolveDuration : 0f);

            foreach (Renderer r in bodyRenderers) if (r != null) r.enabled = false;

            // 2. The lamp and the props it dropped; the lamp light dims out with them.
            var groups = new List<Group>();
            TryGetComponent(out EnemyDeathDrop drops);
            if (drops != null)
            {
                foreach (Transform item in drops.DroppedItems)
                {
                    if (item == null) continue;

                    foreach (LampFireEffect lamp in item.GetComponentsInChildren<LampFireEffect>(true))
                        lamp.FadeOutAndFinish(t.CorpseLampDissolveDuration);

                    var itemRenderers = new List<Renderer>();
                    foreach (Renderer r in item.GetComponentsInChildren<Renderer>(false))
                    {
                        if (r.enabled && !(r is ParticleSystemRenderer)) itemRenderers.Add(r);
                    }
                    groups.Add(Prepare(itemRenderers));
                }
            }
            yield return Burn(groups.ToArray(), t.CorpseLampDissolveDuration);

            // 3. Free everything that belonged to this enemy.
            CorpseCullingHooks.RaiseRemoving(gameObject);
            if (drops != null)
            {
                foreach (Transform item in drops.DroppedItems)
                    if (item != null) Destroy(item.gameObject);
            }
            CorpseOptimizer.NoteDissolved();
            Debug.Log($"[CORPSE] freed '{name}' after {Time.time - startedAt:0.0}s of dissolve ({groups.Count} drop groups)");
            Destroy(gameObject);
        }

        /// <summary>Swaps each renderer to its dissolve variant and measures the world-space height range.</summary>
        private Group Prepare(List<Renderer> renderers)
        {
            var group = new Group { Renderers = renderers.ToArray() };
            if (renderers.Count == 0) return group;

            Bounds bounds = TrueBounds(renderers[0]);
            for (int i = 1; i < renderers.Count; i++) bounds.Encapsulate(TrueBounds(renderers[i]));
            group.Block.SetFloat(MinYId, bounds.min.y);
            group.Block.SetFloat(MaxYId, bounds.max.y);
            group.Block.SetFloat(AmountId, 0f);

            foreach (Renderer r in renderers)
            {
                Material[] mats = r.sharedMaterials;
                for (int m = 0; m < mats.Length; m++)
                    mats[m] = DissolveVariant(mats[m]);
                r.sharedMaterials = mats;
                r.SetPropertyBlock(group.Block);
            }

            return group;
        }

        /// <summary>
        /// Real world bounds of what is drawn. A SkinnedMeshRenderer's own bounds are the animated pose's
        /// padded box (2.5 m tall on a body lying flat), which would make the burn front start and finish at
        /// the wrong moments, so skinned meshes are baked once (only when a dissolve starts) and measured.
        /// </summary>
        private static Bounds TrueBounds(Renderer renderer)
        {
            if (renderer is SkinnedMeshRenderer skinned && skinned.sharedMesh != null)
            {
                var baked = new Mesh();
                skinned.BakeMesh(baked, false);
                baked.RecalculateBounds(); // BakeMesh keeps the bind-pose bounds otherwise
                Bounds local = baked.bounds;
                Matrix4x4 toWorld = skinned.transform.localToWorldMatrix;
                Vector3 c = local.center, e = local.extents;
                Bounds world = new Bounds(toWorld.MultiplyPoint3x4(c), Vector3.zero);
                for (int i = 0; i < 8; i++)
                {
                    Vector3 corner = c + new Vector3((i & 1) == 0 ? -e.x : e.x, (i & 2) == 0 ? -e.y : e.y, (i & 4) == 0 ? -e.z : e.z);
                    world.Encapsulate(toWorld.MultiplyPoint3x4(corner));
                }
                Destroy(baked);
                return world;
            }
            return renderer.bounds;
        }

        private Material DissolveVariant(Material source)
        {
            foreach (MaterialPair pair in materials)
            {
                if (pair.source == source && pair.dissolve != null) return pair.dissolve;
            }
            return source; // no variant: this material simply will not burn
        }

        private static IEnumerator Burn(Group[] groups, float duration)
        {
            if (duration > 0f)
            {
                for (float elapsed = 0f; elapsed < duration; elapsed += Time.deltaTime)
                {
                    SetAmount(groups, Mathf.Clamp01(elapsed / duration));
                    yield return null;
                }
            }
            SetAmount(groups, 1f);
        }

        private static void SetAmount(Group[] groups, float amount)
        {
            foreach (Group g in groups)
            {
                g.Block.SetFloat(AmountId, amount);
                foreach (Renderer r in g.Renderers)
                    if (r != null) r.SetPropertyBlock(g.Block);
            }
        }
    }
}
