// A thin, tunable ripple-ring overlay that sits on top of a Crest water surface (MRM-18 rain
// port). This is the exact same math ported from the Amazing Assets "Dynamic Radial Masks"
// Ripple mask (count=64, Advanced/Additive/ID1/Local) tuned live in the Playground project -
// hand-authored here rather than reproduced as a Shader Graph, matching the precedent set by
// Water.shader/FlareCore.shader/BloodPoolFresnel.shader in this folder. The DRMController /
// DRMLiveObjectsPool scripts (Assets/_Project/Code/Vendor/Dynamic Radial Masks) still drive this
// exactly as they drive the Amazing Assets demo material - the property names below
// (DynamicRadialMasks_Ripple_64_Advanced_Additive_ID1_Local_DATA1/2/3) are generated by
// DRMUtility.GetMaterialPropertyName from (shape=Ripple, count=64, type=Advanced,
// blendMode=Additive, ID=1, scope=Local), so this material is a drop-in target for any
// DRMController configured with that exact combination - nothing here needs to change if the
// DRMController's other settings (radius, intensity, frequency, ...) are retuned.
// Count was bumped from the original 8 to 64 (MRM-18) because 8 concurrent ripple slots
// couldn't keep up with a full rainstorm's collision rate - most raindrops hitting the water
// found the pool already full and silently produced no ripple. The per-count .cginc file is a
// purely mechanical template (array size + unrolled loop bound); the old count=8 variant is
// left in place, unused.
Shader "MrMoonlight/Environment/RippleOverlay"
{
    Properties
    {
        [Header(Ripple)]
        _RippleColor ("Ripple Color", Color) = (1, 1, 1, 1)
        _RippleAlpha ("Ripple Alpha Multiplier", Range(0, 4)) = 1.0
    }

    SubShader
    {
        Tags
        {
            "RenderType" = "Transparent"
            "RenderPipeline" = "UniversalPipeline"
            "Queue" = "Transparent+10"
            "IgnoreProjector" = "True"
        }

        // Renders after the water underneath it (Queue+10) and blends on top.
        Blend SrcAlpha OneMinusSrcAlpha
        ZWrite Off
        ZTest LEqual
        Cull Back

        Pass
        {
            Name "RippleOverlay"
            Tags { "LightMode" = "UniversalForward" }

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Assets/_Project/Code/Vendor/Dynamic Radial Masks/Shaders/DynamicRadialMasks_Ripple_200_Advanced_Additive_ID1_Local.cginc"

            struct Attributes
            {
                float4 positionOS : POSITION;
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float3 positionWS : TEXCOORD0;
            };

            CBUFFER_START(UnityPerMaterial)
                float4 _RippleColor;
                float  _RippleAlpha;
            CBUFFER_END

            Varyings vert(Attributes input)
            {
                Varyings output;
                output.positionWS = TransformObjectToWorld(input.positionOS.xyz);
                output.positionCS = TransformWorldToHClip(output.positionWS);
                return output;
            }

            half4 frag(Varyings input) : SV_Target
            {
                float mask = DynamicRadialMasks_Ripple_200_Advanced_Additive_ID1_Local(input.positionWS, 0.0);
                half alpha = saturate(mask * _RippleAlpha);
                return half4(_RippleColor.rgb, alpha);
            }
            ENDHLSL
        }
    }

    Fallback Off
}
